version: "3.9"

services:
  postgres:
    ports: !reset []
    volumes:
      - pg_data_prod:/var/lib/postgresql/data
    networks:
      - internal

  minio:
    ports: !reset []
    volumes:
      - minio_data_prod:/data
    networks:
      - internal

  app:
    volumes:
      - app_storage_prod:/app/storage-data
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  pg_data_prod:
  minio_data_prod:
  app_storage_prod:
